name: main branch auto ci process srcipt

on:
    push:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest

        env:
            POSTGRES_CONNECTION: ${{ secrets.POSTGRES_CONNECTION }}
            REDIS_CONNECTION: ${{ secrets.REDIS_CONNECTION }}
            CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
            CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
            CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
            JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
            JWT_EXPIRE_DATE: ${{ secrets.JWT_EXPIRE_DATE }}
            DATA_API: ${{ secrets.DATA_API }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install Dependencies
              run: npm install

            - name: Run Tests
              run: npm test

    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.REMOTE_SSH_HOST }}
                  username: ${{ secrets.REMOTE_SSH_USERNAME }}
                  key: ${{ secrets.REMOTE_SSH_KEY }}
                  port: ${{ secrets.REMOTE_SSH_PORT }}
                  script: |
                      cd /home/ubuntu/app/MemeFridge
                      git pull origin master
                      sudo docker compose stop
                      sudo docker container prune -f
                      sudo docker image prune -a -f
                      sudo docker compose up -d
